### ISSUE TITLE
Compatibility with Cilium

### ISSUE THREAD

**Issue by thrashwerk** [jodevsa/wireguard-operator#115]
Has anyone tried using this with Cilium CNI?

My guess it's probably not compatible since this project uses iptables and Cilium does most things with eBPF.

I've installed the operator on a fresh cluster with Cilium 1.13, created the `Wireguard` and `WireguardPeer` objects, got the peer config, used the config in a separate VM but I can't access any resources from the VM on K8s.

The Wireguard agent logs show that it failed to sync Wireguard:
```
2023/10/31 09:02:49 agent: "caller"={"file":"main.go","line":81} "level"=0 "msg"="Received a new state"
2023/10/31 09:02:49 agent/wireguard: "caller"={"file":"wireguard.go","line":199} "level"=0 "msg"="syncing Wireguard"
2023/10/31 09:02:49 agent: "caller"={"file":"main.go","line":84} "msg"="Error while sycncing wireguard" "error"="exit status 1"
2023/10/31 09:02:49 agent/iptables: "caller"={"file":"iptables.go","line":42} "level"=0 "msg"="syncing network policies"
```

**Comment by jodevsa** [comment]
Hey @thrashwerk,


The operator should work regardless of the CNI used as it doesn't really depend on the CNI implementation

**Comment by jodevsa** [comment]
I can offer a live debugging session if your okay with that to try to see what is the problem

**Comment by thrashwerk** [comment]
While it doesn't depend on a CNI implementation it uses iptables and I suppose eBPF could route the packets before they reach iptables. At one place I worked we used iptables to firewall our servers, when we created a K8s cluster with Cilium the iptables firewall no longer worked since eBPF would take over a lot earlier, we had to use Cilium network policies.

Right now I'm running:
K8s 1.27.2
Cilium 1.13.4 (with Kube-proxy replacement)
wireguard-opeartor 2.0.8

In wg-test namespace I created:
```
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: Wireguard
metadata:
  name: "my-cool-vpn"
spec:
  serviceType: "LoadBalancer"
  enableIpForwardOnPodInit: true
```

The VPN pod starts but there's an error in the agent container logs:
```
2023/11/08 12:03:12 agent: "caller"={"file":"main.go","line":81} "level"=0 "msg"="Received a new state"
2023/11/08 12:03:12 agent/wireguard: "caller"={"file":"wireguard.go","line":199} "level"=0 "msg"="syncing Wireguard"
2023/11/08 12:03:12 agent: "caller"={"file":"main.go","line":84} "msg"="Error while sycncing wireguard" "error"="exit status 1"
2023/11/08 12:03:12 agent/iptables: "caller"={"file":"iptables.go","line":42} "level"=0 "msg"="syncing network policies"
```

It fails to sync something but it's not clear what.

**Comment by thrashwerk** [comment]
I checked the agent container in the VPN pod, I don't see any Wireguard interface, only the regular eth0 interface with the pod IP. So maybe there's a problem with creating the interface?

**Comment by thrashwerk** [comment]
So adding a few `fmt.Println` I found out it gets an error here [wireguard.go#L123](https://github.com/jodevsa/wireguard-operator/blob/main/pkg/wireguard/wireguard.go#L123).

Removed the userspace options from the deployment
```
        - --wg-userspace-implementation-fallback
        - wireguard-go
        - --wg-use-userspace-implementation
```
the agent container had created the wg0 interface and now my VM can reach pods in the cluster, so I guess everything works.

**Comment by jodevsa** [comment]
Great debugging skills @thrashwerk!


Would you be interested of adding new boolean attribute to he Wireguard CRD. Something like 


```
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: Wireguard
metadata:
  name: "my-cool-vpn"
spec:
  serviceType: "LoadBalancer"
  enableIpForwardOnPodInit: true
  useWGUserspaceImplemenation: true
```

I'd really appreciate that!

**Comment by thrashwerk** [comment]
> Great debugging skills @thrashwerk!
> 
> Would you be interested of adding new boolean attribute to he Wireguard CRD. Something like
> 
> ```
> apiVersion: vpn.wireguard-operator.io/v1alpha1
> kind: Wireguard
> metadata:
>   name: "my-cool-vpn"
> spec:
>   serviceType: "LoadBalancer"
>   enableIpForwardOnPodInit: true
>   useWGUserspaceImplemenation: true
> ```
> 
> I'd really appreciate that!

Sure, I'll take a lookt at it.
