### ISSUE TITLE
make install: SIGSEGV

### ISSUE THREAD

**Issue by aep** [jodevsa/wireguard-operator#144]
Hi,

i tried looking into if we can extend this project instead of doing our own thing over at https://github.com/kraudcloud/wga

but i might need some help getting started with development.

according to https://book.kubebuilder.io/quick-start.html#create-a-project
you just `make install`  however, in minikube v1.25.2:

```
wireguard-operator make install     
/work/kraud/wireguard-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0c6be]

goroutine 96 [running]:
go/types.(*Checker).handleBailout(0xc0005bca00, 0xc001af7d40)
	/usr/lib/go/src/go/types/check.go:367 +0x88
panic({0xbb8e00?, 0x1297d30?})
	/usr/lib/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xdadaf8, 0x12a0740})
	/usr/lib/go/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
	/usr/lib/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0xdadaf8?, 0x12a0740?})
	/usr/lib/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xdb3fc0, 0x126c5e0}, 0xc0005bca00, 0x12a0740, 0xc001af74b0)
	/usr/lib/go/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc0005bca00, 0xc001a51500, 0x12a0740)
	/usr/lib/go/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc0005bca00, 0xc001a51500, {0xdadb20, 0xc00029c690})
	/usr/lib/go/src/go/types/expr.go:375 +0x30d
go/types.(*Checker).assignment(0xc0005bca00, 0xc001a51500, {0xdadb20, 0xc00029c690}, {0xc85fa6, 0x14})
	/usr/lib/go/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).initConst(0xc0005bca00, 0xc0016607e0, 0xc001a51500)
	/usr/lib/go/src/go/types/assignments.go:126 +0x336
go/types.(*Checker).constDecl(0xc0005bca00, 0xc0016607e0, {0xdb07b8, 0xc0018f0fa0}, {0xdb07b8, 0xc0018f0fc0}, 0x0)
	/usr/lib/go/src/go/types/decl.go:490 +0x348
go/types.(*Checker).objDecl(0xc0005bca00, {0xdb9558, 0xc0016607e0}, 0x0)
	/usr/lib/go/src/go/types/decl.go:191 +0xa49
go/types.(*Checker).packageObjects(0xc0005bca00)
	/usr/lib/go/src/go/types/resolver.go:693 +0x4dd
go/types.(*Checker).checkFiles(0xc0005bca00, {0xc00196c000, 0x5, 0x5})
	/usr/lib/go/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
	/usr/lib/go/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc0002c6fc0, 0xc000fc8aa0)
	/home/aep/.go/pkg/mod/sigs.k8s.io/controller-tools@v0.8.0/pkg/loader/loader.go:283 +0x36a
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc000fc8aa0)
	/home/aep/.go/pkg/mod/sigs.k8s.io/controller-tools@v0.8.0/pkg/loader/loader.go:96 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc00141c600, 0xc000fc8aa0)
	/home/aep/.go/pkg/mod/sigs.k8s.io/controller-tools@v0.8.0/pkg/loader/refs.go:263 +0x2b7
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x53?)
	/home/aep/.go/pkg/mod/sigs.k8s.io/controller-tools@v0.8.0/pkg/loader/refs.go:257 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 26
	/home/aep/.go/pkg/mod/sigs.k8s.io/controller-tools@v0.8.0/pkg/loader/refs.go:255 +0x1c5
make: *** [Makefile:100: manifests] Error 2

```

**Comment by jodevsa** [comment]
Moin @aep,
what `go version` are you using?

**Comment by jodevsa** [comment]
it's working for me with `go version go1.22.0 darwin/arm64`

<img width="1440" alt="Screenshot 2024-02-28 at 21 16 44" src="https://github.com/jodevsa/wireguard-operator/assets/14154314/1bd52dfc-38f9-4e71-885a-d356d5c35932">

> 
however, in minikube v1.25.2
doesn't really matter as you have the error before `kubectl apply` is running

**Comment by jodevsa** [comment]
> i tried looking into if we can extend this project instead of doing our own thing over at https://github.com/kraudcloud/wga

Can you walk me through your use case? looking at the repo which appears to be about creating peers and a server, I think wireguard-operator can acheive your use case without any modification and you can start using it right away

**Comment by aep** [comment]
> go version

`go version go1.22.0 linux/amd64`

> Can you walk me through your use case?

we use it for k8s access. but its alot more fine grained, with only specific routes for ingresses going into the vpn, instead of 0.0.0.0/0

**Comment by jodevsa** [comment]
>  with only specific routes for ingresses going into the vpn, instead of 0.0.0.0/0


AllowedIPs can be modified already. wireguard-operator also supports network policies through iptables where you can ensure that a peer can only access a specific route.


> but i'm half done writing a proper CRD now :|
have fun maintaining more stuff then :D

**Comment by aep** [comment]
> AllowedIPs can be modified already. wireguard-operator also supports network policies through iptables where you can ensure that a peer can only access a specific route.

oh!   #110 was never closed tho?

**Comment by jodevsa** [comment]
just to be clear:


>  with only specific routes for ingresses going into the vpn,
you want a peer A to only be able to access specific IPs?

**Comment by aep** [comment]
> have fun maintaining more stuff then :D

oh yeah..   i cant figure out why the kubebuilder thing is broken tho :(   it looks huuuge

**Comment by aep** [comment]
> just to be clear:
> 
> > with only specific routes for ingresses going into the vpn,
> 
> you want a peer A to only be able to access specific IPs?

yes. thats 1. an nftables thing server side, 2. of course only those ips should be in allowedips in the generated client config too

**Comment by aep** [comment]
oh also this one is missing ip6 forward config in sysctl. easy fix. if i could get it to build

**Comment by jodevsa** [comment]
#110 is about setting the allowedIP in the server side. This is something else. This allows peer B to acess IP X on peer A. it's not related to setting the allowedIps on the generated client config.

**Comment by aep** [comment]
ah! i misread that, thanks

**Comment by jodevsa** [comment]
what version is `/work/kraud/wireguard-operator/bin/controller-gen` ?

**Comment by jodevsa** [comment]
can you try this:


edit the makefile, update CONTROLLER_TOOLS_VERSION to v0.7.0 or v0.9.0

**Comment by aep** [comment]
same result with 0.9 and a fresh checkout

**Comment by jodevsa** [comment]
okay, I have good news, I can reproduce your error after deleting my bin folder

**Comment by aep** [comment]
awesome. going to check back tomorrow :) ttyl

**Comment by jodevsa** [comment]
looks like `CONTROLLER_TOOLS_VERSION ?= v0.14.0` fixes it!

**Comment by jodevsa** [comment]
btw, are you aware that you could try wireguard-operator just by simply running:
```
kubectl apply -f https://github.com/jodevsa/wireguard-operator/releases/download/v2.0.0/release.yaml
```
?

**Comment by aep** [comment]
> btw, are you aware that you could try wireguard-operator just by simply running:
> 
> ```
> kubectl apply -f https://github.com/jodevsa/wireguard-operator/releases/download/v2.0.0/release.yaml
> ```
> 
> ?

Yep but not work on it. 
Thanks for the fix! 

I'll open some PRs for stuff we're missing once I got it running in minikube. Like V6 forwarding and generating a QR code.

**Comment by aep** [comment]
hm im stuck here now 
```
make run
/work/kraud/wireguard-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/work/kraud/wireguard-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
go run ./cmd/manager/main.go
2024-02-29T21:01:02+01:00	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
2024-02-29T21:01:02+01:00	ERROR	setup	unable to start manager	{"error": "--wireguard-container-image flag is not set"}
main.main
	/work/kraud/wireguard-operator/cmd/manager/main.go:87
runtime.main
	/usr/lib/go/src/runtime/proc.go:271
exit status 1
make: *** [Makefile:124: run] Error 1

```




apparantly make run is starting it locally. is there a smart way to just build the docker image and run it inside minikube?
