### ISSUE TITLE
Wireguard CRD does not provide a way to set spec.loadBalancerIP

### ISSUE THREAD

**Issue by winston0410** [jodevsa/wireguard-operator#183]
**Is your feature request related to a problem? Please describe.**
Currently the Wireguard CRD does not provide a way to set `spec.loadBalancerIP` for the `Service` that it will generate. The `spec.address` field is not passed to the `Service` that it will generate as well. If I have a static public IP generated outside K8S, I will not be able to assign that IP to the generated service from the Wireguard CRD now.

**Describe the solution you'd like**
When the `spec.serviceType = LoadBalancer`, pass the `spec.address` to the generated Service at `spec.loadBalancerIP`. No-op if `spec.serviceType = NodePort`

**Describe alternatives you've considered**
An alternative would be having a field called `spec.serviceLoadBalancerIP` that accept IP. If we do this, we will have to duplicate input.

**Additional context**

**Comment by winston0410** [comment]
@jodevsa I think this is a relatively simple and easy feature to implement, is this something you would like to accept, if I create a PR for it?

**Comment by jodevsa** [comment]
Hi @winston0410, of-course! feel free to contribute and do whatever you think is best :) Thanks a lot!
