### ISSUE TITLE
Schedule wireguard agent on specific nodes

### ISSUE THREAD

**Issue by ANBAL534** [jodevsa/wireguard-operator#193]
**Is your feature request related to a problem? Please describe.**
I'd like to schedule wireguard agent on specific nodes. 

The use case would be that sometimes I need to choose from which physical node I need my traffic to go out to the internet when using the VPN. This is specially useful when using on-premise or hybrid kubernetes clusters setups where the infra is located on different datacenters but on the same cluster.

**Describe the solution you'd like**
I'd like to have `nodeName` and `nodeSelector` passed through to the resulting k8s agent deployment for the vpn server

**Describe alternatives you've considered**
Implementing Admission Controller to modify the agent deployment on the fly

**Additional context**
N/A

**Comment by winston0410** [comment]
@ANBAL534 feature added in 2.3.0
