### ISSUE TITLE
Don't send all the traffic through VPN

### ISSUE THREAD

**Issue by anggutie-dev** [jodevsa/wireguard-operator#22]
Hello,

Is there a way to not send all traffic through the VPN?

Currently all traffic is being sent out through the VPN.

Regards

**Comment by jodevsa** [comment]
Hi Anngutie, can you provide me an example of a use case?

**Comment by jodevsa** [comment]
https://join.slack.com/t/wireguard-operator/shared_invite/zt-1pdlczs1f-s3gd0UyAKPUKjhy0VKFfyg

we could also discuss it on slack

**Comment by jodevsa** [comment]
this might be relevant:
https://techoverflow.net/2021/07/09/what-does-wireguard-allowedips-actually-do/

**Comment by anggutie-dev** [comment]
@jodevsa thanks you! I was able to configure it properly using the resource you shared.
