### ISSUE TITLE
Question about usage with Ingress 

### ISSUE THREAD

**Issue by rivetmichael** [jodevsa/wireguard-operator#4]
Hello ! I was looking for a way to use this VPN to restrict access to some Ingress resources in the same k8s cluster using `nginx.ingress.kubernetes.io/whitelist-source-range` annotations for example. Is it possible ?

**Comment by jodevsa** [comment]
hmm, can you set it to `1.1.1.1` and then try:
nslookup google.com // just to verify you are connected

and then try doing doing a lookup with the kube-dns server:

`nslookup default.svc.cluster.local 172.20.0.10`


` default.svc.cluster.local` I don't think this will work as a dns value; there is no way to resolve it

**Comment by jodevsa** [comment]
for example this is how the hostname of service vpn in namespace default should be 
<img width="1096" alt="Screenshot 2022-03-03 at 21 45 59" src="https://user-images.githubusercontent.com/14154314/156650091-3afa1d4f-a749-4269-b58e-a9f3faf30ac4.png">


ah, I totally forgot 🤦 ; you need to include namespace to construct the hostname

**Comment by jodevsa** [comment]
Also, use the kube-dns service IP as the pod ips might change:
<img width="1440" alt="Screenshot 2022-03-03 at 22 05 29" src="https://user-images.githubusercontent.com/14154314/156652828-71704c41-14b1-43a6-9db8-a7de96245898.png">

so 10.48.0.10 in my case

**Comment by jodevsa** [comment]
it works for me with the following config
<img width="461" alt="Screenshot 2022-03-03 at 22 07 58" src="https://user-images.githubusercontent.com/14154314/156653132-43218186-978a-4b6f-8749-8afbd8a897a7.png">


I hope this info will help you figure out what might be the problem :)

**Comment by jodevsa** [comment]
@rivetmichael the operator now automatically defaults to the kube-dns IP as described above :)
