### ISSUE TITLE
Next Release 🎉 

### ISSUE THREAD

**Issue by Matthew-Beckett** [jodevsa/wireguard-operator#46]
With the merge of the following pull requests: 

#36
#37 

And the resolution of:

#45 

A new release should be created, probably version 1.1.0

**Comment by jodevsa** [comment]
Hi @Matthew-Beckett,

Releases are now automated. A release workflow will run and create a release whenever you merged something to main. k8s Release file is also attached to the release assets. example: https://github.com/jodevsa/wireguard-operator/releases/tag/v1.2.0 (check the assets
